apiVersion: apps/v1
kind: Deployment
metadata:
  name: squash-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: squash-operator
  template:
    metadata:
      labels:
        name: squash-operator
    spec:
      serviceAccountName: squash-operator
      containers:
        - name: squash-operator
          image: quay.io/dwojciec/squash-operator:v0.0.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "squash-operator"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
