kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: squash-operator
subjects:
- kind: ServiceAccount
  name: squash-operator
  namespace: squash-server
roleRef:
  kind: ClusterRole
  name: squash-operator
  apiGroup: rbac.authorization.k8s.io
