kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: squash-operator
subjects:
- kind: ServiceAccount
  name: squash-operator
roleRef:
  kind: Role
  name: squash-operator
  apiGroup: rbac.authorization.k8s.io
